# Generated by Django 4.0 on 2021-12-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobileno', models.IntegerField()),
                ('image', models.ImageField(upload_to='pics')),
                ('village', models.TextField()),
                ('password', models.CharField(max_length=20)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
